### ISSUE TITLE
[bug] wall.get error

### ISSUE THREAD

**Issue by nnqq** [SevereCloud/vksdk#147]
Привет, такая ошибка на wall.get, похоже что когда на стене в посте есть вложение "товар" 

```
json: cannot unmarshal bool into Go struct field WallWallpostAttachment.items.attachments.market of type object.MarketMarketItem
```

**Comment by SevereCloud** [comment]
Привет, проверил на стене, где есть товар, ошибки нет.

![image](https://user-images.githubusercontent.com/14944123/97716897-3ab18200-1ad5-11eb-9d1c-e66c7373d09b.png)

Больше похоже на ошибку самого VK, который вернул `false` вместо объекта.

Можно больше подробностей:
- Параметры запроса wall.get
- Версия vksdk

**Comment by nnqq** [comment]
vksdk 2.6.0

```
package main

import (
	"github.com/SevereCloud/vksdk/v2/api"
	"log"
)

func main() {
	vk := api.NewVK("TOKEN")

	_, err := vk.WallGet(api.Params{
		"owner_id": -195263939,
		"count":    100,
		"filter":   "owner",
	})
	log.Print(err)
}

```

**Comment by nnqq** [comment]
https://github.com/SevereCloud/vksdk/pull/148
