### ISSUE TITLE
BanInfo может не быть в GroupsGroup

### ISSUE THREAD

**Issue by ciricc** [SevereCloud/vksdk#199]
Как определить, заблокирован я в сообществе или нет? SDK по умолчанию определяет тип BanInfo как ненулевую структуру.

ВК пишут, что `ban_info` может возвращаться только если получать группу отдельно (через https://dev.vk.com/method/groups.getById). Но опять же, информации о блокировке там может не быть.

**Comment by SevereCloud** [comment]
Возможно стоит попробовать проверить `EndDate`. Но да, нужно и вправду сделать `BanInfo *GroupsGroupBanInfo`

**Comment by ciricc** [comment]
О, круто. Спасибо
