### ISSUE TITLE
Ошибка в object/video.go

### ISSUE THREAD

**Issue by ST380011A** [SevereCloud/vksdk#201]
В нём объявлено свойство, которого нет в документации [VK API](https://dev.vk.com/reference/objects/video):
**// Information whether current user can download the video.
CanDownload BaseBoolInt \`json:"can_download"\`**

Свойство `can_download` может иметь значение **2**, из-за чего функция **MessagesGetHistory** возвращает следующую ошибку:

`json: cannot unmarshal 2 into Go struct field VideoVideo.items.attachments.video.can_download of type *object.BaseBoolInt`

Для исправления этой ошибки предлагаю удалить это свойство из **object/video.go**

**Comment by SevereCloud** [comment]
Спасибо за issue, изменил тип на `int`, фикс уже доступен в [v2.14.1](https://github.com/SevereCloud/vksdk/releases/tag/v2.14.1)
