### ISSUE TITLE
Anonymous can be nil for PollsPoll

### ISSUE THREAD

**Issue by Saoqq** [SevereCloud/vksdk#230]
### Проблема:

Для старых записей ВК может отдавать `PollsPoll` с полем `anonymous=null`

### Пример поста содержащего такой опрос

```
id: 141921
owner_id:  -120254617
// https://vk.com/wall-120254617_141921
```

### RawJson для такого опроса:
```json
"poll": {
    "multiple": false,
    "end_date": 0,
    "closed": false,
    "is_board": false,
    "can_edit": false,
    "can_vote": false,
    "can_report": false,
    "can_share": false,
    "created": 1503383431,
    "id": 272343933,
    "owner_id": -120254617,
    "question": "Who will win the great bicycle race of 2017?",
    "votes": 7319,
    "disable_unvote": false,
    "anonymous": null, <- can't be deserialized correctly
    "answer_id": 0,
    "embed_hash": "272343933_ae2a9be24a30f3d4ed"
}
```
p.s. Поймал эту проблему при использовании `WallGet`

**Comment by SevereCloud** [comment]
Не смог воспроизвести 

<img width="688" alt="image" src="https://user-images.githubusercontent.com/14944123/211188457-a6132578-fdc5-4c5c-bd73-73f78a158e1b.png">

Насколько часто такое происходит?

**Comment by Saoqq** [comment]
Хмм, видимо у меня токен бракованый) 
Использовал достаточно старый токен сейчас, через https://vkhost.github.io/ быстренько затестил другие, с ними не воспроизводится

Закрываю, вопрос решен
