### ISSUE TITLE
cannot unmarshal 2 into Go struct

### ISSUE THREAD

**Issue by Kolsha** [SevereCloud/vksdk#232]
`json: cannot unmarshal 2 into Go struct field VideoVideo.items.last_message.fwd_Messages.attachments.video.can_download of type *object.BaseBoolInt`

Оказывается, поле может принимать и такие значения, не знаю, чей это баг.
```json
"can_download": 2
```

Быстрый фикс:
object/object.go:32:
```go
case bytes.Equal(data, []byte("1")), bytes.Equal(data, []byte("2")), bytes.Equal(data, []byte("true")):
```

**Comment by SevereCloud** [comment]
- Duplicate of #201

Давай проверим версию, фикс должен быть доступен в [v2.14.1](https://github.com/SevereCloud/vksdk/releases/tag/v2.14.1)
