### ISSUE TITLE
Обработка Callback в горутине

### ISSUE THREAD

**Issue by GooG2e** [SevereCloud/vksdk#39]
Сейчас судя по коду функции, которые обрабатывают различные события выполняются последовательно.
Вопрос в том, что некоторые функции могут работать достаточно длительное время и тогда callback может не дождаться ответа "ok". И callback будет повторно подключаться. хотя это событие уже было обработано.
P.S. Это также может делать в коде сам программист далее)

**Comment by SevereCloud** [comment]
Callback должен вернуться `ok` если пользователь точно получил событие. А если операция длительная, программист должен воспользоваться горутинами, очередями, воркерами etc. 
Пихать обработчик в горутину и сразу возвращать `ok` считаю плохой идеей, так как может что-то пойти не так, и пользователь потеряет события.

P.S. Тайм-аут Callback 8 секунд
