### ISSUE TITLE
Использование map[string]interface{}

### ISSUE THREAD

**Issue by amirovn** [SevereCloud/vksdk#68]
Почему бы не использовать map[string]interface{} или map[interface{}]interface{}, вместо map[string]string ?

**Comment by SevereCloud** [comment]
На самом деле я думал про такую реализацию с `map[string]interface{}`. 

Возможно будет в [v1.0](https://github.com/SevereCloud/vksdk/milestone/1)

**Comment by SevereCloud** [comment]
Чтобы не писать в коде `map[string]interface{}{...}`, решил сделать отдельный тип `api.Params{...}`. Так выглядит намного лучше.

Насчет преобразований интерфейсов:
- `bool` преобразуются в `1` или `0`
- Элементы массивов и слайсов перечисляются через запятую
- Вложения преобразуются в формат `<type><owner_id>_<media_id>`
- Клавиатура преобразуется в JSON
- Все остальное проходит через обычный `fmt`

```go
photo := object.PhotosPhoto{
    OwnerID: 321,
    ID:      123,
}
keyboard := object.NewMessagesKeyboard(false, false)
photoSlice := []object.PhotosPhoto{photo, photo}

params := api.Params{
    "test_int":    123,            // "123"
    "test_float":  1.1,            // "1.1"
    "need_likes":  true,           // "1"
    "keyboard":    keyboard,       // `{"buttons":[],"one_time":false}`
    "attachment":  photo,          // "photo321_123"
    "user_ids":    []int{1, 2, 3}, // "1,2,3"
    "attachments": photoSlice,     // "photo321_123,photo321_123"
}
```

Попробовать:

```bash
go get github.com/SevereCloud/vksdk@5466c5a
```

-------

Подумываю еще о создании отдельного модуля **params** для генерации параметров запроса(паттерн Builder)

```go
b := params.MessageSendBuilder()
b.PeerID(123)
b.Random(0)
b.DontParseLinks(false)
b.Message("Test message")

res, err = api.MessageSend(b.Params)
```
