### ISSUE TITLE
Feature Request: Получение UserAccessToken

### ISSUE THREAD

**Issue by forgoty** [SevereCloud/vksdk#70]
Привет. Спасибо за проделанную работу!

Интересует возможность добавления клиента, который инициализируется с помощью логина и пароля, а не через AccessToken. То есть, примерно что-нибудь вот такое:
```go
vk := vkapi.UserInit(username, password)
```

Есть ли в планах реализовать этот функционал? Совпадает ли он с идеей этого модуля?

**Comment by SevereCloud** [comment]
Теперь у нас есть модуль api/oauth
