### ISSUE TITLE
v2: Обновление API с v5.103 до v5.120

### ISSUE THREAD

**Issue by SevereCloud** [SevereCloud/vksdk#95]
# Серьезные изменения в ответе API:

### Объект приложения `AppsApp`

Вместо полей `author_group`, `author_id` теперь `author_owner_id`

### [stories.get](https://vk.com/dev/stories.get), [stories.getReplies](https://vk.com/dev/stories.getReplies), [stories.search](https://vk.com/dev/stories.search)

Вместо двойного массива, теперь массив объектов с полями
- `type`
  - `stories`
  - `community_grouped_stories`
- `stories` при `type=stories`
- `grouped` при `type=community_grouped_stories`
- нужно проверить когда появляется специальная история(например новинки)

_Было_
```json
{
  "count": 1,
  "items": [[{...}]]
}
```

_Стало_
```json
{
  "count": 1,
  "items": [{
    "type": "stories",
    "stories": [{...}]
  }]
}
```

### [stories.getViewers](https://vk.com/dev/stories.getViewers)

_Было_
```json
{
  "count": 16,
  "items": [120158515]
}
```

_Стало_
```json
{
  "count": 16,
  "items": [{
    "is_liked": true,
    "user_id": 120158515
  }]
}
```

### [stories.getViewers](https://vk.com/dev/stories.getViewers) `extended=1`

_Было_
```json
{
  "count": 16,
  "items": [{...}]
}
```

_Стало_
```json
{
  "count": 16,
  "items": [{
    "is_liked": true,
    "user_id": 120158515,
    "user": {...}
  }]
}
```

### [stories.getPhotoUploadServer](https://vk.com/dev/stories.getPhotoUploadServer), [stories.getVideoUploadServer](https://vk.com/dev/stories.getVideoUploadServer) 

Объект истории больше не возвращается(ничего не понял). Вместо него приходит какой-то `upload_result`. 

### [storage.get](https://vk.com/dev/storage.get)

Формат ответа для одного ключа `key` изменился, теперь возвращается объект того же типа, что и при передаче `keys`.

# Новые методы

Возможно эти методы не будут публичными

### [messages.sendService](https://vk.com/dev/messages.sendService)

Нужно для отправки сервисного сообщения(например скриншота)

Параметры:
- `peer_id` - идентификатор назначения
- `action_type` - тип действия
  - `chat_screenshot` - событие создания скриншота

# Обновления

### Объект приложения `AppsApp`

```go
MobileControlsType    int `json:"mobile_controls_type"`
MobileViewSupportType int `json:"mobile_view_support_type"`
HideTabbar            int `json:"hide_tabbar"`
```

### Объект сообщения `MessagesMessage`

```go
ExpireTTL int   `json:"expire_ttl"` // время, через которое сообщение самоуничтожится
```

### Объект настроек диалога `MessagesConversationChatSettings`

```go
IsDisappearing bool   `json:"is_disappearing"` // фантом чат
Theme          string `json:"theme"` // Какая-то цветовая тема
```

### Объект диалога `MessagesConversation`

```go
SortID        struct {
	MajorID int `json:"major_id"`
	MinorID int `json:"minor_id"`
} `json:"sort_id"`
```

### [account.getInfo](https://vk.com/dev/account.getInfo)

```go
LinkRedirects map[string]string `json:"link_redirects"`
```

### [messages.createChat](https://vk.com/dev/messages.createChat)

Новые параметры:
- `copy_from_peer_id` - создать новый чат из чата 
- `is_disappearing` - если `1`, будет создан фантом чат

### [messages.send](https://vk.com/dev/messages.send)

Новые параметры:
- `silent` - если `1`, отправит сообщение без уведомления
- `expire_ttl` - время, через которое сообщение самоуничтожится

---

Пишите в комментарии, если найдете изменения в API.

**Comment by slmatthew** [comment]
В объекте аудиосообщения появились поля `transcript` (string) и `transcript_state` (string).

`transcript` появляется только при `transcript_state = "done"`

```json
 {
       "type": "audio_message",
       "audio_message": {
          "id": 123,
          "owner_id": 305360617,
          "duration": 1,
          "waveform": [],
          "link_ogg": "...",
          "link_mp3": "...",
          "access_key": "...",
          "transcript": "здесь текст с транскрипцией",
          "transcript_state": "done"
       }
}
```

Не знаю, было ли это здесь, но в объекте сообщения с голосовым сообщением есть поле `was_listened` (bool)
